#!/bin/sh
#
# Disposable rootless-Podman SSH fixture for fork-only zmx UI tests.
#
# The default ZMX_REPO is ../zmx relative to the rootshell repository. The
# image build context is always that checkout, never an implicit host path.
# `start` prints KEY=VALUE records suitable for a runner; `run` wraps a test
# command and guarantees cleanup.

set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
repo_root=$(CDPATH= cd -- "$script_dir/../.." && pwd -P)
containerfile=$script_dir/Containerfile
podman_bin=${PODMAN_BIN:-podman}
zmx_repo=${ZMX_REPO:-../zmx}
fixture_image=${ZMX_FIXTURE_IMAGE:-rootshell-zmx-fixture:local}
fixture_user=zmx
fixture_host=127.0.0.1
fixture_state_dir=

usage() {
    cat <<'EOF'
Usage:
  zmx-fixture.sh start [--env-file FILE]
  zmx-fixture.sh run [--env-file FILE] -- COMMAND [ARG...]
  zmx-fixture.sh env STATE_DIR
  zmx-fixture.sh seed STATE_DIR SUFFIX [SUFFIX...]
  zmx-fixture.sh exec STATE_DIR COMMAND [ARG...]
  zmx-fixture.sh stop STATE_DIR
  zmx-fixture.sh self-check
  zmx-fixture.sh help

Environment:
  ZMX_REPO              zmx checkout used as the image build context
  ZMX_FIXTURE_IMAGE     local image tag (default: rootshell-zmx-fixture:local)
  PODMAN_BIN            Podman executable (default: podman)

The start environment records are:
  ZMX_FIXTURE_STATE_DIR, ZMX_FIXTURE_CONTAINER_ID,
  ZMX_FIXTURE_HOST, ZMX_FIXTURE_PORT, ZMX_FIXTURE_USERNAME,
  ZMX_FIXTURE_PRIVATE_KEY, ZMX_FIXTURE_SESSION_PREFIX,
  ZMX_FIXTURE_ZMX_REVISION
EOF
}

die() {
    echo "zmx-fixture: $*" >&2
    exit 1
}

need_command() {
    command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

validate_suffix() {
    case "$1" in
        ''|*[!ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-]*)
            die "session suffix must contain only letters, digits, '.', '_' or '-': $1"
            ;;
    esac
}

validate_state_dir() {
    case "$1" in
        /*) ;;
        *) die "state directory must be an absolute path: $1" ;;
    esac
    [ -f "$1/state" ] || die "not a zmx fixture state directory: $1"
}

state_value() {
    key=$1
    state_file=$2
    sed -n "s/^${key}=//p" "$state_file" | sed -n '1p'
}

load_state() {
    fixture_state_dir=$1
    validate_state_dir "$fixture_state_dir"
    state_file=$fixture_state_dir/state
    fixture_container_id=$(state_value container_id "$state_file")
    fixture_container_name=$(state_value container_name "$state_file")
    fixture_port=$(state_value port "$state_file")
    fixture_prefix=$(state_value prefix "$state_file")
    fixture_key=$(state_value key "$state_file")
    fixture_known_hosts=$(state_value known_hosts "$state_file")
    fixture_revision=$(state_value revision "$state_file")
    [ -n "$fixture_container_id" ] || die "state has no container id: $fixture_state_dir"
    [ -n "$fixture_port" ] || die "state has no SSH port: $fixture_state_dir"
    [ -n "$fixture_prefix" ] || die "state has no session prefix: $fixture_state_dir"
    [ -f "$fixture_key" ] || die "fixture key is missing: $fixture_key"
}

run_podman() {
    "$podman_bin" "$@"
}

require_rootless_podman() {
    rootless=$(run_podman info --format '{{.Host.Security.Rootless}}' 2>/dev/null) || die 'cannot inspect Podman rootless mode'
    case "$rootless" in
        true|True|TRUE) ;;
        *) die "Podman is not running rootless (reported: $rootless)" ;;
    esac
}

control_ssh() {
    # Deliberately use a state-local known_hosts file: no host key or SSH
    # configuration is written to the developer's home directory. The port is
    # the dynamic loopback mapping returned by `podman port`.
    ssh \
        -o BatchMode=yes \
        -o ConnectTimeout=3 \
        -o StrictHostKeyChecking=accept-new \
        -o "UserKnownHostsFile=$fixture_known_hosts" \
        -i "$fixture_key" \
        -p "$fixture_port" \
        "$fixture_user@$fixture_host" "$@"
}

write_env() {
    env_output=$1
    {
        printf 'ZMX_FIXTURE_STATE_DIR=%s\n' "$fixture_state_dir"
        printf 'ZMX_FIXTURE_CONTAINER_ID=%s\n' "$fixture_container_id"
        printf 'ZMX_FIXTURE_HOST=%s\n' "$fixture_host"
        printf 'ZMX_FIXTURE_PORT=%s\n' "$fixture_port"
        printf 'ZMX_FIXTURE_USERNAME=%s\n' "$fixture_user"
        printf 'ZMX_FIXTURE_PRIVATE_KEY=%s\n' "$fixture_key"
        printf 'ZMX_FIXTURE_SESSION_PREFIX=%s\n' "$fixture_prefix"
        printf 'ZMX_FIXTURE_ZMX_REVISION=%s\n' "$fixture_revision"
    } > "$env_output"
    chmod 600 "$env_output"
}

print_env() {
    load_state "$1"
    write_env "$fixture_state_dir/env"
    cat "$fixture_state_dir/env"
}

kill_prefixed_sessions() {
    # `zmx list --short` emits names only. Every name is checked locally before
    # a kill command is sent, and the prefix is generated by this coordinator.
    session_list=$fixture_state_dir/session-list
    if ! control_ssh 'ZMX_SESSION_PREFIX= zmx list --short' > "$session_list" 2>/dev/null; then
        return 0
    fi
    while IFS= read -r session_name; do
        case "$session_name" in
            "$fixture_prefix"-*)
                # Session names created by this coordinator use the same
                # restricted alphabet as suffixes. Ignore any unexpected
                # name rather than interpolating it into a remote command.
                session_suffix=${session_name#"$fixture_prefix"-}
                case "$session_suffix" in
                    ''|*[!ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-]*) continue ;;
                esac
                control_ssh "ZMX_SESSION_PREFIX= zmx kill --force $session_name" >/dev/null 2>&1 || true
                ;;
        esac
    done < "$session_list"
    rm -f "$session_list"
}

cleanup_state() {
    cleanup_state_dir=$1
    [ -d "$cleanup_state_dir" ] || return 0
    [ -f "$cleanup_state_dir/state" ] || return 0
    load_state "$cleanup_state_dir" 2>/dev/null || true
    remove_status=0
    if [ -n "${fixture_container_id:-}" ]; then
        kill_prefixed_sessions || true
        run_podman rm -f "$fixture_container_id" >/dev/null 2>&1 || remove_status=$?
    fi
    # Retain the container ID only if removal failed, which makes failures
    # diagnosable without leaving routine state behind.
    if [ "$remove_status" -ne 0 ] || { [ -n "${fixture_container_id:-}" ] && run_podman inspect "$fixture_container_id" >/dev/null 2>&1; }; then
        echo "zmx-fixture: cleanup failed; retained container $fixture_container_id" >&2
        return 1
    fi
    rm -rf "$cleanup_state_dir"
}

on_interrupt() {
    if [ -f "${fixture_state_dir:-}/state" ]; then
        cleanup_state "$fixture_state_dir" || true
    else
        cleanup_partial_container
        [ -z "${fixture_state_dir:-}" ] || rm -rf "$fixture_state_dir"
    fi
    exit 1
}

on_exit() {
    exit_status=$?
    trap - 0
    if [ "$exit_status" -ne 0 ] && [ -n "$fixture_state_dir" ]; then
        if [ -f "$fixture_state_dir/state" ]; then
            cleanup_state "$fixture_state_dir" || true
        else
            cleanup_partial_container
            rm -rf "$fixture_state_dir"
        fi
    fi
    exit "$exit_status"
}

cleanup_partial_container() {
    if [ -n "${fixture_container_id:-}" ]; then
        run_podman rm -f "$fixture_container_id" >/dev/null 2>&1 || true
    fi
}

build_image() {
    zmx_repo_abs=$zmx_repo
    case "$zmx_repo_abs" in
        /*) ;;
        *) zmx_repo_abs=$repo_root/$zmx_repo_abs ;;
    esac
    zmx_repo_abs=$(CDPATH= cd -- "$zmx_repo_abs" && pwd -P) || die "cannot resolve ZMX_REPO: $zmx_repo"
    [ -f "$zmx_repo_abs/build.zig" ] || die "ZMX_REPO has no build.zig: $zmx_repo_abs"
    zmx_revision=$(git -C "$zmx_repo_abs" rev-parse --verify HEAD 2>/dev/null || printf '%s' unknown)
    echo "zmx-fixture: building $fixture_image from zmx $zmx_revision" >&2
    run_podman build --pull=missing \
        --file "$containerfile" \
        --tag "$fixture_image" \
        --build-arg "ZMX_REVISION=$zmx_revision" \
        "$zmx_repo_abs" >&2
    fixture_revision=$zmx_revision
}

start_fixture() {
    need_command "$podman_bin"
    need_command ssh
    need_command ssh-keygen
    [ -f "$containerfile" ] || die "missing Containerfile: $containerfile"
    require_rootless_podman

    fixture_state_dir=$(mktemp -d "${TMPDIR:-/tmp}/rootshell-zmx-fixture.XXXXXX")
    chmod 700 "$fixture_state_dir"
    trap on_interrupt INT TERM HUP
    trap on_exit 0

    fixture_key=$fixture_state_dir/id_ed25519
    fixture_known_hosts=$fixture_state_dir/known_hosts
    umask 077
    ssh-keygen -q -t ed25519 -N '' -f "$fixture_key" -C rootshell-zmx-fixture
    chmod 600 "$fixture_key"
    chmod 644 "$fixture_key.pub"

    fixture_nonce=$(basename "$fixture_state_dir" | tr -cd 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789')
    fixture_prefix=rs-xcui-$fixture_nonce
    fixture_container_name=$fixture_prefix-container

    build_image
    fixture_container_id=$(run_podman run --detach \
        --name "$fixture_container_name" \
        --publish "$fixture_host::22" \
        "$fixture_image" \
        sleep infinity)
    fixture_container_id=$(printf '%s\n' "$fixture_container_id" | sed -n '1p')
    [ -n "$fixture_container_id" ] || die 'Podman returned no container ID'

    fixture_port=$(run_podman port "$fixture_container_id" 22/tcp | sed -n '1s/.*:\([0-9][0-9]*\)$/\1/p')
    case "$fixture_port" in
        ''|*[!0-9]*) die 'Podman returned no dynamic SSH port' ;;
    esac

    cat > "$fixture_state_dir/state" <<EOF
container_id=$fixture_container_id
container_name=$fixture_container_name
port=$fixture_port
prefix=$fixture_prefix
key=$fixture_key
known_hosts=$fixture_known_hosts
revision=$fixture_revision
EOF
    chmod 600 "$fixture_state_dir/state"

    run_podman cp "$fixture_key.pub" "$fixture_container_id:/home/$fixture_user/.ssh/authorized_keys"
    run_podman exec "$fixture_container_id" chown "$fixture_user:$fixture_user" "/home/$fixture_user/.ssh/authorized_keys"
    run_podman exec "$fixture_container_id" chmod 600 "/home/$fixture_user/.ssh/authorized_keys"
    run_podman exec "$fixture_container_id" passwd -d "$fixture_user" >/dev/null
    run_podman exec --detach "$fixture_container_id" sh -c 'mkdir -p /run/sshd && ssh-keygen -A && exec /usr/sbin/sshd -D -e' >/dev/null

    ssh_ready=false
    ready_attempt=0
    while [ "$ready_attempt" -lt 30 ]; do
        if control_ssh true >/dev/null 2>&1; then
            ssh_ready=true
            break
        fi
        ready_attempt=$((ready_attempt + 1))
        sleep 1
    done
    [ "$ssh_ready" = true ] || die "SSH did not become ready on $fixture_host:$fixture_port"

    write_env "$fixture_state_dir/env"
    cat "$fixture_state_dir/env"
}

seed_sessions() {
    load_state "$1"
    shift
    [ "$#" -gt 0 ] || die 'seed requires at least one session suffix'
    for suffix do
        validate_suffix "$suffix"
        session_name=$fixture_prefix-$suffix
        control_ssh "ZMX_SESSION_PREFIX= zmx run $session_name -d /bin/bash" >/dev/null
        printf '%s\n' "$session_name"
    done
}

exec_remote() {
    load_state "$1"
    shift
    [ "$#" -gt 0 ] || die 'exec requires a command'
    control_ssh "$@"
}

stop_fixture() {
    load_state "$1"
    cleanup_state "$fixture_state_dir"
}

self_check() {
    need_command sh
    need_command sed
    need_command mktemp
    need_command ssh
    need_command ssh-keygen
    need_command "$podman_bin"
    [ -r "$containerfile" ] || die "cannot read Containerfile: $containerfile"
    sh -n "$0"
    echo 'zmx-fixture: self-check passed'
}

command_name=${1:-help}
shift || true
case "$command_name" in
    help|-h|--help)
        usage
        ;;
    self-check)
        self_check
        ;;
    start)
        env_file=
        if [ "${1:-}" = '--env-file' ]; then
            [ "$#" -ge 2 ] || die '--env-file requires a path'
            env_file=$2
            shift 2
        fi
        [ "$#" -eq 0 ] || die "unexpected start argument: $1"
        start_fixture
        if [ -n "$env_file" ]; then
            cp "$fixture_state_dir/env" "$env_file"
            chmod 600 "$env_file"
        fi
        trap - INT TERM HUP 0
        ;;
    run)
        env_file=
        if [ "${1:-}" = '--env-file' ]; then
            [ "$#" -ge 2 ] || die '--env-file requires a path'
            env_file=$2
            shift 2
        fi
        [ "${1:-}" = '--' ] || die 'run requires -- before the command'
        shift
        [ "$#" -gt 0 ] || die 'run requires a command'
        start_fixture
        if [ -n "$env_file" ]; then
            cp "$fixture_state_dir/env" "$env_file"
            chmod 600 "$env_file"
        fi
        # Export the state-local environment to the wrapped command. Keeping
        # the command's endpoint file inside the fixture state means the
        # unconditional cleanup below removes it together with the container.
        set -a
        . "$fixture_state_dir/env"
        set +a
        run_status=0
        "$@" || run_status=$?
        cleanup_state "$fixture_state_dir" || run_status=1
        trap - INT TERM HUP 0
        exit "$run_status"
        ;;
    env)
        [ "$#" -eq 1 ] || die 'env requires STATE_DIR'
        print_env "$1"
        ;;
    seed)
        [ "$#" -ge 2 ] || die 'seed requires STATE_DIR and one suffix'
        state_dir=$1
        shift
        seed_sessions "$state_dir" "$@"
        ;;
    exec)
        [ "$#" -ge 2 ] || die 'exec requires STATE_DIR and a command'
        exec_remote "$@"
        ;;
    stop)
        [ "$#" -eq 1 ] || die 'stop requires STATE_DIR'
        stop_fixture "$1"
        ;;
    *)
        die "unknown command: $command_name (try help)"
        ;;
esac
